/**
* @file This script is auto-generated by create-nitro-module and should not be edited.
*
* @description This script applies a workaround for Android by modifying the '<ModuleName>OnLoad.cpp' file.
* It reads the file content and removes the 'margelo/nitro/' string from it. This enables support for custom package names.
*
* @module create-nitro-module
*/
const path = require('node:path')
const { writeFile, readFile } = require('node:fs/promises')




const androidWorkaround = async () => {
  const androidOnLoadFile = path.join(
    process.cwd(),
    'nitrogen/generated/android',
    'M3OnLoad.cpp'
  )


  const str = await readFile(androidOnLoadFile, { encoding: 'utf8' })
  let newContent = str.replace(/com\/margelo\/nitro\/m3\/com\.m3\./g, 'com/m3/')
  newContent = newContent.replace(/com\/margelo\/nitro\/m3\//g, 'com/m3/')
  await writeFile(androidOnLoadFile, newContent)
  console.log(`✅ Applied refined Android workaround to ${path.basename(androidOnLoadFile)}`)
}
androidWorkaround()